#!/bin/bash
version=`python3 -c "import electrum; print(electrum.version.ELECTRUMSYS_VERSION)"`
sig=`./run_electrumsys -w $SIGNING_WALLET signmessage $SIGNING_ADDRESS $version`
echo "{ \"version\":\"$version\", \"signatures\":{ \"$SIGNING_ADDRESS\":\"$sig\"}}"
